name: qrscan
description: A Plug-in for dart, which help you scanning barcode and qrcode with android device.
version: 0.3.4
homepage: https://github.com/leyan95/qrcode_scanner

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.shinow.qrscan
        pluginClass: QrscanPlugin
